/*
 * libtcore
 *
 * Copyright (c) 2013 Samsung Electronics Co. Ltd. All rights reserved.
 * Copyright (c) 2013 Intel Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __TYPE_COMMAND_H__
#define __TYPE_COMMAND_H__

#ifdef __cplusplus
extern "C"
{
#endif

#include <type/common.h>

/** Commands */
typedef enum {
	/* Modem */
	TCORE_COMMAND_MODEM = TCORE_COMMAND | TCORE_TYPE_MODEM,
	TCORE_COMMAND_MODEM_SET_POWER_STATUS,
	TCORE_COMMAND_MODEM_SET_FLIGHTMODE,
	TCORE_COMMAND_MODEM_GET_FLIGHTMODE,
	TCORE_COMMAND_MODEM_GET_IMEI,
	TCORE_COMMAND_MODEM_GET_VERSION,

	/* SIM */
	TCORE_COMMAND_SIM = TCORE_COMMAND | TCORE_TYPE_SIM,
	TCORE_COMMAND_SIM_GET_IMSI,
	TCORE_COMMAND_SIM_GET_ECC,
	TCORE_COMMAND_SIM_GET_ICCID,
	TCORE_COMMAND_SIM_GET_LANGUAGE,
	TCORE_COMMAND_SIM_SET_LANGUAGE,
	TCORE_COMMAND_SIM_GET_CALL_FORWARDING_INFO,
	TCORE_COMMAND_SIM_GET_MESSAGE_WAITING_INFO,
	TCORE_COMMAND_SIM_SET_MESSAGE_WAITING_INFO,
	TCORE_COMMAND_SIM_GET_MAILBOX_INFO,
	TCORE_COMMAND_SIM_SET_MAILBOX_INFO,
	TCORE_COMMAND_SIM_GET_MSISDN,
	TCORE_COMMAND_SIM_GET_SPN,
	TCORE_COMMAND_SIM_GET_CPHS_NET_NAME,
	TCORE_COMMAND_SIM_GET_SP_DISPLAY_INFO,
	TCORE_COMMAND_SIM_REQ_AUTHENTICATION,
	TCORE_COMMAND_SIM_VERIFY_PINS,
	TCORE_COMMAND_SIM_VERIFY_PUKS,
	TCORE_COMMAND_SIM_CHANGE_PINS,
	TCORE_COMMAND_SIM_DISABLE_FACILITY,
	TCORE_COMMAND_SIM_ENABLE_FACILITY,
	TCORE_COMMAND_SIM_GET_FACILITY,
	TCORE_COMMAND_SIM_GET_LOCK_INFO,
	TCORE_COMMAND_SIM_REQ_APDU,
	TCORE_COMMAND_SIM_REQ_ATR,

	/* NETWORK */
	TCORE_COMMAND_NETWORK = TCORE_COMMAND | TCORE_TYPE_NETWORK,
	TCORE_COMMAND_NETWORK_GET_IDENTITY_INFO,
	TCORE_COMMAND_NETWORK_SEARCH,
	TCORE_COMMAND_NETWORK_CANCEL_SEARCH,
	TCORE_COMMAND_NETWORK_SELECT_AUTOMATIC,
	TCORE_COMMAND_NETWORK_SELECT_MANUAL,
	TCORE_COMMAND_NETWORK_GET_SELECTION_MODE,
	TCORE_COMMAND_NETWORK_SET_PREFERRED_PLMN,
	TCORE_COMMAND_NETWORK_GET_PREFERRED_PLMN,
	TCORE_COMMAND_NETWORK_SET_MODE,
	TCORE_COMMAND_NETWORK_GET_MODE,
	TCORE_COMMAND_NETWORK_GET_NEIGHBORING_CELL_INFO,

	/* CALL */
	TCORE_COMMAND_CALL = TCORE_COMMAND | TCORE_TYPE_CALL,
	TCORE_COMMAND_CALL_DIAL,
	TCORE_COMMAND_CALL_ANSWER,
	TCORE_COMMAND_CALL_END,
	TCORE_COMMAND_CALL_SEND_DTMF,
	TCORE_COMMAND_CALL_HOLD,
	TCORE_COMMAND_CALL_ACTIVE,
	TCORE_COMMAND_CALL_SWAP,
	TCORE_COMMAND_CALL_JOIN,
	TCORE_COMMAND_CALL_SPLIT,
	TCORE_COMMAND_CALL_TRANSFER,
	TCORE_COMMAND_CALL_DEFLECT,
	TCORE_COMMAND_CALL_SET_ACTIVE_LINE,
	TCORE_COMMAND_CALL_GET_ACTIVE_LINE,
	TCORE_COMMAND_CALL_SET_VOLUME_INFO,
	TCORE_COMMAND_CALL_GET_VOLUME_INFO,
	TCORE_COMMAND_CALL_SET_SOUND_PATH,
	TCORE_COMMAND_CALL_SET_MUTE,
	TCORE_COMMAND_CALL_GET_MUTE_STATUS,
	TCORE_COMMAND_CALL_SET_SOUND_RECORDING,
	TCORE_COMMAND_CALL_SET_SOUND_EQUALIZATION,

	/* SS */
	TCORE_COMMAND_SS = TCORE_COMMAND | TCORE_TYPE_SS,
	TCORE_COMMAND_SS_SET_BARRING,
	TCORE_COMMAND_SS_GET_BARRING_STATUS,
	TCORE_COMMAND_SS_CHANGE_BARRING_PASSWORD,
	TCORE_COMMAND_SS_SET_FORWARDING,
	TCORE_COMMAND_SS_GET_FORWARDING_STATUS,
	TCORE_COMMAND_SS_SET_WAITING,
	TCORE_COMMAND_SS_GET_WAITING_STATUS,
	TCORE_COMMAND_SS_SET_CLI,
	TCORE_COMMAND_SS_GET_CLI_STATUS,
	TCORE_COMMAND_SS_SEND_USSD_REQUEST,

	/* PHONEBOOK */
	TCORE_COMMAND_PHONEBOOK = TCORE_COMMAND | TCORE_TYPE_PHONEBOOK,
	TCORE_COMMAND_PHONEBOOK_GET_INFO,
	TCORE_COMMAND_PHONEBOOK_READ_RECORD,
	TCORE_COMMAND_PHONEBOOK_UPDATE_RECORD,
	TCORE_COMMAND_PHONEBOOK_DELETE_RECORD,

	/* SMS */
	TCORE_COMMAND_SMS = TCORE_COMMAND | TCORE_TYPE_SMS,
	TCORE_COMMAND_SMS_SEND_SMS,
	TCORE_COMMAND_SMS_READ_IN_SIM,
	TCORE_COMMAND_SMS_WRITE_IN_SIM,
	TCORE_COMMAND_SMS_DELETE_IN_SIM,
	TCORE_COMMAND_SMS_GET_COUNT,
	TCORE_COMMAND_SMS_SET_CB_CONFIG,
	TCORE_COMMAND_SMS_GET_CB_CONFIG,
	TCORE_COMMAND_SMS_GET_PARAMETERS,
	TCORE_COMMAND_SMS_SET_PARAMETERS,
	TCORE_COMMAND_SMS_SEND_DELIVER_REPORT,
	TCORE_COMMAND_SMS_SET_SCA,
	TCORE_COMMAND_SMS_GET_SCA,
	TCORE_COMMAND_SMS_SET_MEMORY_STATUS,
	TCORE_COMMAND_SMS_SET_MESSAGE_STATUS,

	/* SAT */
	TCORE_COMMAND_SAT = TCORE_COMMAND | TCORE_TYPE_SAT,
	TCORE_COMMAND_SAT_REQ_ENVELOPE,
	TCORE_COMMAND_SAT_REQ_TERMINAL_RESPONSE,
	TCORE_COMMAND_SAT_REQ_USER_CONFIRMATION,

	/* SAP */
	TCORE_COMMAND_SAP = TCORE_COMMAND | TCORE_TYPE_SAP,
	TCORE_COMMAND_SAP_REQ_CONNECT,
	TCORE_COMMAND_SAP_REQ_DISCONNECT,
	TCORE_COMMAND_SAP_GET_ATR,
	TCORE_COMMAND_SAP_REQ_TRANSFER_APDU,
	TCORE_COMMAND_SAP_REQ_TRANSPORT_PROTOCOL,
	TCORE_COMMAND_SAP_REQ_POWER_OPERATION,
	TCORE_COMMAND_SAP_GET_CARDREADER_STATUS,

	/* GPS */
	TCORE_COMMAND_GPS = TCORE_COMMAND | TCORE_TYPE_GPS,
	TCORE_COMMAND_GPS_CONFIRM_MEASURE_POS,
	TCORE_COMMAND_GPS_SET_FREQUENCY_AIDING,

	/* PS */
	TCORE_COMMAND_PS = TCORE_COMMAND | TCORE_TYPE_PS,
	TCORE_COMMAND_PS_DEFINE_CONTEXT,
	TCORE_COMMAND_PS_ACTIVATE_CONTEXT,
	TCORE_COMMAND_PS_DEACTIVATE_CONTEXT,

} TcoreCommand;

#ifdef __cplusplus
}
#endif

#endif	/* __TYPE_COMMAND_H__ */
