/*
 * libtcore
 *
 * Copyright (c) 2013 Samsung Electronics Co. Ltd. All rights reserved.
 * Copyright (c) 2013 Intel Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __TYPE_NOTIFICATION_H__
#define __TYPE_NOTIFICATION_H__

#include <type/common.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
	TCORE_SERVER_NOTIFICATION_UNKNOWN = 0,

	TCORE_SERVER_NOTIFICATION = TCORE_NOTIFICATION | TCORE_TYPE_SERVER,
	TCORE_SERVER_NOTIFICATION_SERVER_RUN,
	TCORE_SERVER_NOTIFICATION_ADDED_PLUGIN,
	TCORE_SERVER_NOTIFICATION_REMOVED_PLUGIN,
	TCORE_SERVER_NOTIFICATION_ADDED_COMMUNICATOR,
	TCORE_SERVER_NOTIFICATION_REMOVED_COMMUNICATOR,
	TCORE_SERVER_NOTIFICATION_ADDED_HAL,
	TCORE_SERVER_NOTIFICATION_REMOVED_HAL,
	TCORE_SERVER_NOTIFICATION_ADDED_STORAGE,
	TCORE_SERVER_NOTIFICATION_REMOVED_STORAGE,
	TCORE_SERVER_NOTIFICATION_ADDED_MODEM_PLUGIN,
	TCORE_SERVER_NOTIFICATION_REMOVED_MODEM_PLUGIN,
	TCORE_SERVER_NOTIFICATION_EXIT,
	TCORE_SERVER_NOTIFICATION_MODEM_ERR
} TcoreServerNotification;

typedef enum {
	TCORE_NOTIFICATION_UNKNOWN = 0,

	TCORE_NOTIFICATION_CALL = TCORE_NOTIFICATION | TCORE_TYPE_CALL,
	TCORE_NOTIFICATION_CALL_STATUS_IDLE,
	TCORE_NOTIFICATION_CALL_STATUS_ACTIVE,
	TCORE_NOTIFICATION_CALL_STATUS_HELD,
	TCORE_NOTIFICATION_CALL_STATUS_DIALING,
	TCORE_NOTIFICATION_CALL_STATUS_ALERT,
	TCORE_NOTIFICATION_CALL_STATUS_INCOMING,
	TCORE_NOTIFICATION_VIDEO_CALL_STATUS_IDLE,
	TCORE_NOTIFICATION_VIDEO_CALL_STATUS_ACTIVE,
	TCORE_NOTIFICATION_VIDEO_CALL_STATUS_DIALING,
	TCORE_NOTIFICATION_VIDEO_CALL_STATUS_ALERT,
	TCORE_NOTIFICATION_VIDEO_CALL_STATUS_INCOMING,
	TCORE_NOTIFICATION_CALL_INFO_HELD,
	TCORE_NOTIFICATION_CALL_INFO_ACTIVE,
	TCORE_NOTIFICATION_CALL_INFO_JOINED,
	TCORE_NOTIFICATION_CALL_INFO_MO_FORWARD_UNCONDITIONAL,
	TCORE_NOTIFICATION_CALL_INFO_MO_FORWARD_CONDITIONAL,
	TCORE_NOTIFICATION_CALL_INFO_MO_FORWARDED,
	TCORE_NOTIFICATION_CALL_INFO_MO_WAITING,
	TCORE_NOTIFICATION_CALL_INFO_MO_BARRED_OUTGOING,
	TCORE_NOTIFICATION_CALL_INFO_MO_BARRED_INCOMING,
	TCORE_NOTIFICATION_CALL_INFO_MO_DEFLECTED,
	TCORE_NOTIFICATION_CALL_INFO_MT_FORWARDED,
	TCORE_NOTIFICATION_CALL_INFO_MT_DEFLECTED,
	TCORE_NOTIFICATION_CALL_INFO_TRANSFERED,
	TCORE_NOTIFICATION_CALL_SOUND_RINGBACK_TONE,
	TCORE_NOTIFICATION_CALL_SOUND_WBAMR,
	TCORE_NOTIFICATION_CALL_SOUND_EQUALIZATION,
	TCORE_NOTIFICATION_CALL_SOUND_CLOCK_STATUS,

	TCORE_NOTIFICATION_SS = TCORE_NOTIFICATION | TCORE_TYPE_SS,
	TCORE_NOTIFICATION_SS_INFO,
	TCORE_NOTIFICATION_SS_USSD,

	TCORE_NOTIFICATION_MODEM = TCORE_NOTIFICATION | TCORE_TYPE_MODEM,
	TCORE_NOTIFICATION_MODEM_POWER,
	TCORE_NOTIFICATION_MODEM_FLIGHT_MODE,

	TCORE_NOTIFICATION_SIM = TCORE_NOTIFICATION | TCORE_TYPE_SIM,
	TCORE_NOTIFICATION_SIM_TYPE,
	TCORE_NOTIFICATION_SIM_STATUS,

	TCORE_NOTIFICATION_SAT = TCORE_NOTIFICATION | TCORE_TYPE_SAT,
	TCORE_NOTIFICATION_SAT_PROACTIVE_CMD,
	TCORE_NOTIFICATION_SAT_SESSION_END,
	TCORE_NOTIFICATION_SAT_CALL_CTRL_RESULT,
	TCORE_NOTIFICATION_SAT_MO_SM_CTRL_RESULT,

	TCORE_NOTIFICATION_SAP = TCORE_NOTIFICATION | TCORE_TYPE_SAP,
	TCORE_NOTIFICATION_SAP_STATUS,

	TCORE_NOTIFICATION_NETWORK = TCORE_NOTIFICATION | TCORE_TYPE_NETWORK,
	TCORE_NOTIFICATION_NETWORK_REGISTRATION_STATUS,
	TCORE_NOTIFICATION_NETWORK_LOCATION_CELLINFO,
	TCORE_NOTIFICATION_NETWORK_RSSI,
	TCORE_NOTIFICATION_NETWORK_TIMEINFO,
	TCORE_NOTIFICATION_NETWORK_IDENTITY,

	TCORE_NOTIFICATION_PS = TCORE_NOTIFICATION | TCORE_TYPE_PS,
	TCORE_NOTIFICATION_PS_CALL_STATUS,
	TCORE_NOTIFICATION_PS_IPCONFIG,

	TCORE_NOTIFICATION_SMS = TCORE_NOTIFICATION | TCORE_TYPE_SMS,
	TCORE_NOTIFICATION_SMS_INCOM_MSG,			/* This is an unsolicited Incoming SMS Event*/
	TCORE_NOTIFICATION_SMS_CB_INCOM_MSG,		/* This is an unsolicited Incoming cell broadcast message*/
	TCORE_NOTIFICATION_SMS_MEMORY_STATUS,		/* This event is an unsolicited event indicating SIM memory status */
	TCORE_NOTIFICATION_SMS_DEVICE_READY,		/* Device Ready indication */
	TCORE_NOTIFICATION_SMS_ETWS_INCOM_MSG,		/* This is an unsolicited Incoming ETWS message*/

	TCORE_NOTIFICATION_PHONEBOOK = TCORE_NOTIFICATION | TCORE_TYPE_PHONEBOOK,
	TCORE_NOTIFICATION_PHONEBOOK_STATUS,

	TCORE_NOTIFICATION_GPS = TCORE_NOTIFICATION | TCORE_TYPE_GPS,
	TCORE_NOTIFICATION_GPS_ASSIST_DATA,
	TCORE_NOTIFICATION_GPS_MEASURE_POSITION,
	TCORE_NOTIFICATION_GPS_RESET_ASSIST_DATA,

	TCORE_NOTIFICATION_CUSTOM = TCORE_NOTIFICATION | TCORE_TYPE_CUSTOM,
} TcoreNotification;

#ifdef __cplusplus
}
#endif

#endif
